### ISSUE TITLE
[support] ios install fail `native module cannot be null`

### ISSUE THREAD

**Issue by Thomazella** [adjust/react_native_sdk#50]
Hey guys, the `npm` & `react-native link` install in the readme didn't quite fly on my environment.

similar issue: https://github.com/adjust/react_native_sdk/issues/34

I got the native module cannot be null right off the bat. After debugging I noticed the native module was missing and assumed it to be a config/install/link error.

After that I tried doing pods but it messed the whole thing up. 🤔 
Currently rolled back to a stable state and will try again tomorrow.

if I add the package thru npm, it doesn't depend on pods in any way, right? I tried linking manually but didn't see a .framework listed in xcode 🤔 

Any help is appreciated.

npm v6.4.1
node v11.3.0
```
"dependencies": {
    "@expo/react-native-action-sheet": "1.0.2",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-remove-console": "6.8.5",
    "bugsnag-react-native": "2.7.0",
    "ethereum-regex": "1.1.3",
    "immutability-helper": "2.4.0",
    "instabug-reactnative": "8.0.12",
    "lodash": "4.17.4",
    "moment": "2.18.1",
    "numeral": "2.0.6",
    "re-reselect": "1.0.1",
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-adjust": "4.17.0",
    "react-native-android-keyboard-adjust": "1.1.1",
    "react-native-camera": "1.1.2",
    "react-native-charts-wrapper": "0.4.3",
    "react-native-device-info": "0.21.5",
    "react-native-fbsdk": "0.7.0",
    "react-native-gesture-recognizers": "git://git@github.com:rdy/react-native-gesture-recognizers.git",
    "react-native-iphone-x-helper": "1.0.2",
    "react-native-keyboard-aware-scroll-view": "0.5.0",
    "react-native-keyboard-manager": "4.0.13-5",
    "react-native-linear-gradient": "2.4.0",
    "react-native-masked-text": "1.6.4",
    "react-native-mixpanel": "git://git@github.com:gabrieletondi/react-native-mixpanel.git",
    "react-native-onesignal": "3.0.7",
    "react-native-popup-menu": "0.12.2",
    "react-native-qrcode-scanner": "1.0.1",
    "react-native-safe-area-view": "0.6.0",
    "react-native-size-matters": "0.1.0",
    "react-native-splash-screen": "3.1.1",
    "react-native-swipeout": "2.3.1",
    "react-native-touch-id": "4.0.3",
    "react-native-vector-icons": "4.4.0",
    "react-native-walkthrough-tooltip": "0.2.0",
    "react-native-xml2js": "1.0.3",
    "react-navigation": "1.0.0-beta.13",
    "react-redux": "5.0.5",
    "redux": "3.7.1",
    "redux-actions": "2.2.1",
    "redux-saga": "0.15.4",
    "redux-storage": "4.1.2",
    "redux-storage-decorator-debounce": "1.1.3",
    "redux-storage-decorator-filter": "1.1.8",
    "redux-storage-engine-reactnativeasyncstorage": "1.0.5",
    "reselect": "3.0.1",
    "socket.io": "2.0.3",
    "validate.js": "0.12.0",
    "why-did-you-update": "0.1.0"
  },
  "devDependencies": {
    "@storybook/addon-actions": "3.2.10",
    "@storybook/addon-links": "3.2.10",
    "@storybook/react-native": "3.2.10",
    "babel-eslint": "7.1.0",
    "babel-jest": "18.0.0",
    "babel-preset-react-native": "2.0.0",
    "eslint": "3.9.1",
    "eslint-config-airbnb": "12.0.0",
    "eslint-plugin-flowtype": "2.25.0",
    "eslint-plugin-import": "1.16.0",
    "eslint-plugin-jsx-a11y": "2.2.3",
    "eslint-plugin-react": "6.6.0",
    "flow-bin": "0.45.0",
    "jest": "21.2.1",
    "prop-types": "15.6.0",
    "react-dom": "16.0.0-alpha.12",
    "react-test-renderer": "15.4.2"
```

**Comment by Thomazella** [comment]
actually,
`pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'`

this *was* added automatically to my podfile. Maybe I needed to `pod install` ? But the instructions clearly have an OR there 🤔

**Comment by uerceg** [comment]
Hm. Weird.

Not sure what caused the error on your `react-native link` step. Can you maybe paste output which that command gives you?

From what I know `react-native link` command is a bit weird and in case you are using Cocoapods for your iOS app (which you do, since Podfile exists in your `ios` folder), `react-native link` will actually try to link iOS part of the plugin via Podfile if plugin which is attempted to be linked (our SDK in this case) contains Podspec file (which is true for our SDK).

So, I would say you do one of the following things:

1. If you wanna use Cocoapods, leave that line in Podfile and use `pod install` which should add our SDK as a dependency to your iOS app Xcode project via Pods.
2. If you do not want to use Cocoapods, remove that Adjust SDK dependency line from your Podfile, but in order to make `react-native link` to link our SDK properly, one (to me unclear) thing needs to be done in your Podfile: Below last `pod` declaration, add line which says `# Add new pods below this line`.

So literally for example, Podfile should look like this:

```
platform :ios, '9.0'

target 'Adjust4170LinkIssue' do

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'DevSupport',
  'RCTText',
  'RCTAnimation',
  'RCTImage',
  'RCTNetwork',
  'RCTVibration'
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

# Add new pods below this line

end
```

After this, try to run `react-native link` and hopefully it should link our plugin properly.

Test I did was to create empty RN app to which I have added Podfile (but never ran `pod install`, so I just had it there, which was enough for RN to figure out that it should link stuff via Pods if possible) and then I installed our SDK via `npm`.  Podfile looked like this (without that line I mentioned):

```
platform :ios, '9.0'

target 'Adjust4170LinkIssue' do

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'DevSupport',
  'RCTText',
  'RCTAnimation',
  'RCTImage',
  'RCTNetwork',
  'RCTVibration'
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

end
```

After that I ran `react-native link` and got this:

```
➜  Adjust4170LinkIssue react-native link
rnpm-install info Linking react-native-adjust ios dependency
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined
Please file an issue here: https://github.com/facebook/react-native/issues

Cannot read property 'match' of undefined

TypeError: Cannot read property 'match' of undefined
    at findLineToAddPod (/Users/uerceg/Projects/ReactNative/Adjust4170LinkIssue/node_modules/react-native/local-cli/link/pods/findLineToAddPod.js:22:17)
    at getLinesToAddEntry (/Users/uerceg/Projects/ReactNative/Adjust4170LinkIssue/node_modules/react-native/local-cli/link/pods/registerNativeModule.js:36:12)
    at registerNativeModulePods (/Users/uerceg/Projects/ReactNative/Adjust4170LinkIssue/node_modules/react-native/local-cli/link/pods/registerNativeModule.js:25:27)
    at Object.registerNativeModule [as register] (/Users/uerceg/Projects/ReactNative/Adjust4170LinkIssue/node_modules/react-native/local-cli/link/ios/common/registerNativeModule.js:13:5)
    at Object.keys.forEach.platform (/Users/uerceg/Projects/ReactNative/Adjust4170LinkIssue/node_modules/react-native/local-cli/link/link.js:74:16)
    at Array.forEach (<anonymous>)
    at linkDependency (/Users/uerceg/Projects/ReactNative/Adjust4170LinkIssue/node_modules/react-native/local-cli/link/link.js:44:32)
```

Now I added that mentioned line to Podfile and made it look like this:

```
platform :ios, '9.0'

target 'Adjust4170LinkIssue' do

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'DevSupport',
  'RCTText',
  'RCTAnimation',
  'RCTImage',
  'RCTNetwork',
  'RCTVibration'
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

# Add new pods below this line

end
```

And then ran `react-native link` again:

```
➜  Adjust4170LinkIssue react-native link
rnpm-install info Linking react-native-adjust ios dependency
rnpm-install info Platform 'ios' module react-native-adjust has been successfully linked
rnpm-install info Linking react-native-adjust android dependency
rnpm-install info Platform 'android' module react-native-adjust has been successfully linked
```

Lemme know if you managed to make it work.

Cheers

**Comment by Thomazella** [comment]
@uerceg I'll put some extra time on this one to figure out why it failed... I'll post back soon

**Comment by uerceg** [comment]
Sure, no problemo. Ping us when ever you find some time. Looking forward to hear from you on this one.

**Comment by Thomazella** [comment]
I'm trying again. react-native-link says this:
```
rnpm-install info Linking bugsnag-react-native android dependency
rnpm-install info Android module bugsnag-react-nativehas been successfully linked
rnpm-install info iOS module bugsnag-react-native is already linked
rnpm-install info Linking instabug-reactnative android dependency
rnpm-install info Android module instabug-reactnativehas been successfully linked
rnpm-install info iOS module instabug-reactnative is already linked
ruby: warning: shebang line ending with \r may cause problems
rnpm-install info Android module react-native-adjust is already linked
rnpm-install info iOS module react-native-adjust is already linked
rnpm-install info Linking react-native-android-keyboard-adjust android dependency
rnpm-install info Android module react-native-android-keyboard-adjust has been successfully linked
rnpm-install info Linking react-native-camera androiddependency
rnpm-install info Android module react-native-camera has been successfully linked
rnpm-install info iOS module react-native-camera is already linked
rnpm-install info Linking react-native-charts-wrapperandroid dependency
rnpm-install info Android module react-native-charts-wrapper has been successfully linked
rnpm-install info Android module react-native-device-info is already linked
rnpm-install info iOS module react-native-device-infois already linked
rnpm-install info Android module react-native-fbsdk is already linked
rnpm-install info iOS module react-native-fbsdk is already linked
rnpm-install info iOS module react-native-keyboard-manager is already linked
rnpm-install info Linking react-native-linear-gradient android dependency
rnpm-install info Android module react-native-linear-gradient has been successfully linked
rnpm-install info iOS module react-native-linear-gradient is already linked
```

**Comment by Thomazella** [comment]
above comment was me just redoing the readme, basically, I added the line to the pod file and ran `react-native link react-native-adjust`

```
react-native link react-native-adjust
Scanning folders for symlinks in /Users/vamac/Code/foton/squirrel-mobile/node_modules (15ms)
rnpm-install info Android module react-native-adjust is already linked
rnpm-install info Linking react-native-adjust ios dependency
rnpm-install info iOS module react-native-adjust has been successfully linked
```

**Comment by Thomazella** [comment]
think I just fixed it. Will post after lunch

**Comment by Thomazella** [comment]
Here's how I fixed it, really simple actually:

in Xcode: project > Build Phases > Link Binary With Libraries drop down
click the plus sign > add other > browse to node_modules/react-native-adjust/ios > select the .xcodeproject file
`libAdjustSdk.a` now shows in previous list > add it.

that's it.

**Comment by uerceg** [comment]
Sorry for not following up on this one, but glad it worked for you. Pretty interesting and thanks for sharing the solution. Will close the issue and feel free to reopen it if it pops up again in the future.

Cheers!

**Comment by amarnathsdr** [comment]
I have exactly the same problem and I also link manually with Xcode but I still have the same 'native module cannot be null' ...
